# This is a basic workflow to help you get started with Actions

name: Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          touch hello-world.md
          echo "Hello world!" >> hello-world.md

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          path: hello-world.md

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: artifact
          path: ./
          

